describe('Add bank account', function(){
    // Add bank account with Valid data  when new user 
    it("Add bank account successfull", function(){
        cy.visit('/')
        cy.get('#username')
        .type('Gul.S')
        cy.get('#password')  
        .type('Gul12')
        cy.get('.MuiButton-label').click()
        cy.get('[data-test=user-onboarding-next] > .MuiButton-label')
        .click()
        cy.get('#bankaccount-bankName-input')
        .type('Kotak')
        cy.get('#bankaccount-routingNumber-input')
        .type('123456789')
        cy.get('#bankaccount-accountNumber-input')
        .type('121212121212')
        cy.get('[data-test=bankaccount-submit] > .MuiButton-label')
        .click()
        cy.get('[data-test=user-onboarding-next] > .MuiButton-label')
        .click()

    })
});

// Valid data when user is old
it("Old user, Add bank account successfull", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Gul.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-bankaccounts] > .MuiListItemIcon-root')
    .click()
    //cy.get('.MuiButton-label > .MuiSvgIcon-root').click()
    cy.get('[data-test=bankaccount-new] > .MuiButton-label').click()
    cy.get('#bankaccount-bankName-input')
    .type('KOtak')
    cy.get('#bankaccount-routingNumber-input')
    .type('123456789')
    cy.get('#bankaccount-accountNumber-input')
   .type('121212121212')
    cy.get('[data-test=bankaccount-submit] > .MuiButton-label')
   .click()
   
})

// Invalid Routing Number
it("Invalid Routing number", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Gul.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-bankaccounts] > .MuiListItemIcon-root')
    .click()
    //cy.get('.MuiButton-label > .MuiSvgIcon-root').click()
    cy.get('[data-test=bankaccount-new] > .MuiButton-label').click()
    cy.get('#bankaccount-bankName-input')
    .type('KOtak')
    cy.get('#bankaccount-routingNumber-input')
    .type('1234')
    cy.get('#bankaccount-routingNumber-input-helper-text')
    .should("have.text", "Must contain a valid routing number")
    //cy.get('#bankaccount-accountNumber-input')
   //.type('121212121212')
   // cy.get('[data-test=bankaccount-submit] > .MuiButton-label')
   //.click()

})

// Invalid Bank account number
it("Invalid Bank account number", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Gul.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-bankaccounts] > .MuiListItemIcon-root')
    .click()
    //cy.get('.MuiButton-label > .MuiSvgIcon-root').click()
    cy.get('[data-test=bankaccount-new] > .MuiButton-label').click()
    cy.get('#bankaccount-bankName-input')
    .type('KOtak')
    cy.get('#bankaccount-routingNumber-input')
    .type('123456789')
    cy.get('#bankaccount-accountNumber-input')
   .type('121212')
   
})
//Blank Bank name field
it("Blank Bank name", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Gul.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-bankaccounts] > .MuiListItemIcon-root')
    .click()
    //cy.get('.MuiButton-label > .MuiSvgIcon-root').click()
    cy.get('[data-test=bankaccount-new] > .MuiButton-label').click()
    cy.get('#bankaccount-bankName-input')
    .focus()
      .blur()
      .click()

})
// All blank fields
it("Blank fields", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Gul.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-bankaccounts] > .MuiListItemIcon-root')
    .click()
    cy.get('[data-test=bankaccount-new] > .MuiButton-label').click()
    cy.get('#bankaccount-bankName-input')
    .focus()
    .blur()
    .click()
    cy.get('#bankaccount-routingNumber-input')
    .focus()
    .blur()
    .click()
    cy.get('#bankaccount-accountNumber-input')
    .focus()
    .blur()
    .click()

})